### ISSUE TITLE
[Feature]Add English word to Anki

### ISSUE THREAD

**Issue by yagamilighttuski** [ClearlyKyle/Language-Learning-With-Anki#1]
Greetings! I am thinking is it possible to make it work on English? Cuz sometimes, while watching CrashCourse or lectures on YouTube, key concepts or jargon appear on the screen that I want to capture and add to` Anki`.  If this extension can work on English, i can just click a word then screenshot the key concepts and add it to `Anki`. BTW, it works smoothly on other languages, thanks for your efforts.

**Comment by ClearlyKyle** [comment]
Hello, I didn't know that English would behave differently, for sure this can be something I can have a look at.

**Comment by yagamilighttuski** [comment]
It works perfect now. Wow it's such a big help! Thank you very much! You really use your tech knowledge making world a better place. Words cannot express my gratitude. Wishing you all the best!
