### ISSUE TITLE
[Feature]Work on Netflix

### ISSUE THREAD

**Issue by yagamilighttuski** [ClearlyKyle/Language-Learning-With-Anki#2]
Apologies for reaching out again 😔. I hope this message finds you well. Since I don't write code myself-just knowing some basics- I wonder is it a lot of work to make this extension work on netflix as well? 

If it's hard I don't want to burden you with additional tasks. So maybe I should try to learn some javascript and do it myself in the future. If it's a relatively straightforward addition and you're open to it during your free time, that would be immensely appreciated. Thank you for your time.

**Comment by ClearlyKyle** [comment]
Currently I don't use Netflix with the "language reactor" extension so I haven't look at adding support for Anki to it yet. I do think it should be easy enough as I imagine all the element names for the dictionary and word location would be the same, I will try it out some time later.

**Comment by yagamilighttuski** [comment]
Thank you so much!

**Comment by LennyChenLaw** [comment]
I also have a similar need because I found that there are many dubbed anime and TV shows on Netflix and subtitle proofreading seems very well done, which is quite helpful for language learning. I tried to make some modifications, but ultimately, I failed to make it work.
I tried to revise the if statement to :
```javascript
if (window.location.href.includes("youtube.com/watch") || window.location.href.includes("netflix.com/watch"))
```
and added a function to distinguish between netflix and youtube so as to get their URL
```javascript
    function getVideoPlatform()
    {
        const youtubePattern = /youtube\.com\/watch\?v=/;
        const netflixPattern = /netflix\.com\/watch\//;

        const url = window.location.href;

        if (youtubePattern.test(url))
        {
            return "youtube";
        } else if (netflixPattern.test(url))
        {
            return "netflix";
        } else
        {
            return "unknown";
        }
    }
```
then a function to generate netflix timestamp and a if statement to differentiate
```javascript
    function timestampGen(url, time)
    {
        url = url.split('?')[0];
        time = time | 0;
        url = url + '?t=' + time;
        return url;
    }
        if (platform === "youtube")
        {
            current_time = document.querySelector(".video-stream").currentTime.toFixed() || 0;
        } else if (platform === "netflix")
        {
            current_time = timestampGen() || 0;
        } else
        {
            console.error("Unsupported platform");
            return; // Exit the function if the platform is unsupported
        }

        var timestamped_url;

        if (platform === "youtube")
        {
            timestamped_url = "https://youtu.be/" + videoId + "?t=" + current_time;
        } else if (platform === "netflix")
        {
            timestamped_url = "https://www.netflix.com/watch/" + videoId + "?t=" + current_time;
        }
```
I also changed JSON file to `"matches": [
                "*://*.youtube.com/watch*",
                "*://*.netflix.com/watch*"
            ],` but it seems i just keep get the error `Uncaught TypeError: Cannot read properties of null (reading 'currentTime')`
