### ISSUE TITLE
[Issue]Video link FailedToGetID

### ISSUE THREAD

**Issue by yagamilighttuski** [ClearlyKyle/Language-Learning-With-Anki#3]
I hope this message finds you well. I've come across an issue related to URLs. The issule look like this `<a href="https://youtu.be/FailedToGetID?t=30">Video Link</a>`. (Below is more detailed image). It's kinda weird that it works perfectly with English, i didn't have English card with URL problem. But when it comes to German and Japanese, it usually doesn't function well. I've tested different youtube channels. Turns out it doesn't seem to matter about channels; they both have this issue."
1. The German channel i used for test: [Easy German](https://www.youtube.com/@EasyGerman)          [Learn German Relaxed with Gabriel](https://www.youtube.com/@GermanRelaxedGabriel)
2. The Japanese channel i used for test: [あかね的日本語教室](https://www.youtube.com/@Akane-JapaneseClass)              [EASY JAPANESE PODCAST](https://www.youtube.com/@EASYJAPANESE)
While it's not a major problem, I wanted to bring it to your attention. Feel free to address it whenever it's convenient for you. Thanks for your time and efforts.
![fail](https://github.com/ClearlyKyle/Language-Learning-With-Anki/assets/78994336/8d59ad8f-3336-4161-8290-4cf3369facf6).
![fail2](https://github.com/ClearlyKyle/Language-Learning-With-Anki/assets/78994336/09b2e852-6563-4f54-b16c-dfb00fdb8eda)

**Comment by ClearlyKyle** [comment]
Hello, thanks for telling me about this. I have submitted a fix for it, should be working as expected now!

**Comment by yagamilighttuski** [comment]
Wow that's so quick! Yeah it works perfect now. Thank you!

**Comment by ClearlyKyle** [comment]
Great to hear! Glad to help. Any more issues, just write again 😀
