### ISSUE TITLE
Noob question about usage

### ISSUE THREAD

**Issue by momoongithub** [ClearlyKyle/Language-Learning-With-Anki#5]
Excuse me! I have installed Language Reactor chrome extension and AnkiConnect plugin, but I still don’t know how to create an Anki flash card by LR. I can’t find the Anki button and setting page as follows.Could you please help me?
![Snip20240527_2](https://github.com/ClearlyKyle/Language-Learning-With-Anki/assets/165360662/b8701f69-06db-4bbd-9e28-aa12708a698f)
![settings](https://github.com/ClearlyKyle/Language-Learning-With-Anki/assets/165360662/47ef0371-a9dd-423a-bed5-257d33540ac1)

**Comment by ClearlyKyle** [comment]
Hello, first make sure you have downloaded and added the extension to chrome. 

1. Enter chrome://extensions/ to your browser address bar
2. Flip Developer mode toggle
3. Now you will see Load unpacked action enabled
4. Add the Language-Learning-With-Anki extension.

To check its added, look for the puzzle piece in the top right, it should list LLW_Anki in the active extensions. Click this to get to the settings screen. Make sure the Language Reactor extension is also on. 

Close and reopen YouTube, as the extension runs when YouTube is first opened.

**Comment by momoongithub** [comment]
I am sorry, but where can I find the "Language-Learning-With-Anki extension"?🥺

**Comment by ClearlyKyle** [comment]
First you need to download the repo. 

Go to the main page of the [repo](https://github.com/ClearlyKyle/Language-Learning-With-Anki) and look for the blue "code" button. 

From there you should be able to" download .zip", which contains the extensions. You then need to unzip the file into a folder. This is the folder in which you want to add to chrome as an unpacked extension, as described in the previous comment.

Here is an image of the download button
![image1](https://github.com/ClearlyKyle/Language-Learning-With-Anki/assets/24228375/2cb2c1f5-808a-4d22-b0d2-f532a1f0f2f9)

And here is which folder you want to load the unpack from
![image2](https://github.com/ClearlyKyle/Language-Learning-With-Anki/assets/24228375/9460cd68-0079-4664-8905-b9eb65e70fe1)

Hope that makes sense 😁

**Comment by momoongithub** [comment]
I made it!Thank you sooooo much for your detailed instructions!!!🫶🏻

**Comment by ClearlyKyle** [comment]
No problem, glad to help. Write again if you have any more issues
