### ISSUE TITLE
Example source and Audio

### ISSUE THREAD

**Issue by momoongithub** [ClearlyKyle/Language-Learning-With-Anki#6]
I‘ve been using this extension for a while and it has greatly improved the efficiency of my language learning👍🏻.Now I encounter two problems:
1、In example source, how can I choose both "current" and "Tatoeba" rather than either?
2、Is it possible to send the original audio of example sentences to Anki?

**Comment by ClearlyKyle** [comment]
Hello, 

1 - Having an option to add both is a great idea, this shouldn't be too hard to add. I will add the options of "both" and "none" so you can save either both types or no examples at all. 

2 - I haven't looked at any audio downloading yet. For my own cards, I just use the [AwesomeTTS](https://ankiweb.net/shared/info/1436550454) Anki plugin.

**Comment by momoongithub** [comment]
Now I can add both of them to Anki.Original audio just sounds more natural than TTS, but not necessary.Thanks a million for your help!👏🏻

**Comment by ClearlyKyle** [comment]
No problem. I agree with the audio, ideally I would like to get video audio for the subtitles too.
