### ISSUE TITLE
New in usage, getting error: "Anki Fetch Return Error! cannot create note because it is empty"

### ISSUE THREAD

**Issue by AndresDavidArcos** [ClearlyKyle/Language-Learning-With-Anki#7]
When i click on te Anki button to add the word from language reactor to my anki, it says the error "Anki Fetch Return Error! cannot create note because it is empty"

**Comment by ClearlyKyle** [comment]
Are you not setting the screenshot field in the settings?

**Comment by ClearlyKyle** [comment]
From my testing, what ever your top field is in your note type, has to be filled with something. So make sure you are setting this field to something in the extensions settings.

**Comment by AndresDavidArcos** [comment]
Thanks for the answer, which is the note type here? 
![anki](https://github.com/user-attachments/assets/3dad3896-1d66-48af-b059-0908c789d08f)

**Comment by ClearlyKyle** [comment]
The "Card" option is the note type made in Anki, going to: Tools >Manage Note Types

When you look at the note type, there will be a list of fields. These fields are filled with data gathered by the extension. The field at the top must always have a value for the extension to create a flashcard. 

In your image, you are sending everything to the same field, they should all be different or set them to the blank option.

**Comment by AndresDavidArcos** [comment]
Thanks, it worked for me, nice extension

**Comment by ClearlyKyle** [comment]
Glad to hear it 😃 if you have any more issues, feel free to ask
